### PR TITLE
Create Prueba 6

### PR DESCRIPTION
**Pull request by Emilio1945**
I am pushing all buttons to answer this pull request

### CODE REVIEW

**Comment by Emilio1945** [comment]
No se qué hacer

**Comment by Santiago1270** [comment]
Accept

**Comment by Emilio1945** [comment]
I am trying to accept the Pull Request from SANTIAGO1270

**Comment by Emilio1945** [comment]
I am trying to accept an invitation to collaborate from Santiago1270, but find it difficult to do so. I am pushing all buttons to see if at leat one button does it

**Comment by Santiago1270** [comment]
What is this?

**Comment by Santiago1270** [comment]
Did I do it?

**Comment by Emilio1945** [comment]
I am confused.

**Comment by Santiago1270** [comment]
I was able to accept the invitation of Emilio1945 to collaborate

**Pull request merged**
